title: Pablo Arrighi
description: Independent Quantum Technology Expertise
baseurl: ""
url: "https://pja35.github.io"

theme: minima

header_pages:
  - advisory.md
  - expertise.md
  - contact.md

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
